#!/bin/bash
docker run -ti --rm -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/aoki//eclipse/.eclipse:/home/developer/.eclipse -v /home/aoki//eclipse/workspace:/home/developer/workspace  --name docker-eclipse aoki/docker-eclipse
